language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=flake8
install: pip install tox
script: 
  - tox -e $TOX_ENV
services: 
  - mongodb
  - redis-server
before_script:
    # timer is needed in order to get mongo to properly initialize on travis-ci
    # See https://github.com/travis-ci/travis-ci/issues/1967#issuecomment-42008605
  - sleep 15
  - mongo eve_test --eval 'db.addUser("test_user", "test_pw");'
branches:
  only:
    - master
    - develop
